name: num_to_words
description: An extension method to convert an integer number to its representation in words
version: 0.0.3
repository: https://github.com/hazzik/num_to_words.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
