name: num_to_words
description: An extension method to convert an integer number to its representation in words
version: 1.0.1
repository: https://github.com/hazzik/num_to_words.dart

environment:
  sdk: '^3.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.14.4
