name: Dart

on:
  push: {}
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1.4

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test
  
  publish:
    runs-on: ubuntu-latest

    needs: test

    if: ${{ github.ref_type == 'tag' }}

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1.4
      - name: Setup credentials
        run: | 
          mkdir -p ~/.pub-cache 
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "refreshToken":"${{ secrets.PUB_DEV_REFRESH_TOKEN }}",
            "accessToken":"expired",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 0
          }
          EOF

      - name: Publish package
        run: dart pub publish -f
